export MAKEFILE_NAME = GNUmakefile.gnustep

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = videooverlay

videooverlay_OBJC_FILES = main.m

ifeq ($(GNUSTEP_TARGET_OS), mingw32)
videooverlay_INCLUDE_DIRS = \
  -IC:/gstreamer/include/libxml2 \
  -IC:/gstreamer/include/glib-2.0 \
  -IC:/gstreamer/lib/glib-2.0/include \
  -IC:/gstreamer/include \
  -IC:/gstreamer/include/gstreamer-1.0
endif

ifeq ($(GNUSTEP_TARGET_OS), mingw32)
  videooverlay_LIB_DIRS += \
    -LC:/gstreamer/bin
endif

videooverlay_TOOL_LIBS = \
  -lglib-2.0-0 \
	-lgobject-2.0-0 \
	-lgmodule-2.0-0 \
	-lgthread-2.0-0 \
	-lgstreamer-1.0 \
	-lgstbase-1.0 \
	-lgstvideo-1.0

ADDITIONAL_TOOL_LIBS = -lgnustep-gui

include $(GNUSTEP_MAKEFILES)/tool.make
