language: c
compiler:
  - gcc
  - clang
script: ./autogen.sh ${USE_GLES2---disable-gles2} ${USE_OPENGL---disable-opengl} ${USE_EGL---disable-egl} ${USE_GLX---disable-glx} && make
branches:
  only:
    - ci
before_install:
  - sudo add-apt-repository ppa:gstreamer-developers/ppa -y
  - sudo apt-get update
  - sudo apt-get install autotools-dev automake autoconf libtool gtk-doc-tools python2.7-dev gstreamer1.0-plugins-base-dbg libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgstreamer1.0-0-dbg libegl1-mesa-dev libegl1-mesa-drivers libgles2-mesa-dev mesa-utils-extra
env:
  - USE_GLX= USE_OPENGL=
  - USE_EGL= USE_GLES2=
  - USE_EGL= USE_OPENGL= USE_GLES2=
  - USE_EGL= USE_GLX= USE_OPENGL= USE_GLES2=
