language: c
compiler:
  - gcc
  - clang
script: ./autogen.sh && make && make check
branches:
  only:
    - ci
before_install:
  - sudo add-apt-repository ppa:gstreamer-developers/ppa
  - sudo apt-get update
  - sudo apt-get install autotools-dev automake autoconf libtool gtk-doc-tools python2.7-dev gstreamer1.0 gst-plugins-base1.0
