language: c
compiler:
  - gcc
  - clang
script: ./travis-autogen-wrapper.sh && make
branches:
  only:
    - ci
before_install:
  - sudo add-apt-repository ppa:gstreamer-developers/ppa -y
  - sudo apt-get update
  - sudo apt-get install autotools-dev automake autoconf libtool gtk-doc-tools python2.7-dev gstreamer1.0-plugins-base-dbg libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgstreamer1.0-0-dbg libegl1-mesa-dev libegl1-mesa-drivers libgles2-mesa-dev mesa-utils-extra
env:
  - DISABLE_GLX= DISABLE_EGL=1 DISABLE_OPENGL= DISABLE_GLES2=1
  - DISABLE_GLX=1 DISABLE_EGL= DISABLE_OPENGL=1 DISABLE_GLES2=
  - DISABLE_GLX=1 DISABLE_EGL= DISABLE_OPENGL= DISABLE_GLES2=
  - DISABLE_GLX= DISABLE_EGL= DISABLE_OPENGL= DISABLE_GLES2=
